In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np 

from IPython.display import display

In [27]:
# Caminho para o arquivo Parquet
caminho_parquet = r"C:\Users\Pichau\INMET\TODAS_ESTACOES\TODAS_ESTACOES_CONCATENADO.parquet"

# Ler o arquivo Parquet
df = pd.read_parquet(caminho_parquet)

In [28]:
pd.set_option('display.max_columns', None)  # Exibe todas as colunas

df.head(1)

,Dt_Hr,timestamp,Lat,Long,Alt,Precip,Pres_Atm,Pres_Atm_max,Pres_Atm_min,Rad,Temp_Amb,Pto_Orv,Temp_Amb_max,Temp_Amb_min,Pto_Orv_max,Pto_Orv_min,Umidade_max,Umidade_min,Umidade,Vento_dir,Vento_raj,Vento_vel,ESTACAO,estacao_do_ano,hora,turno,PRECIPITAÇÃO TOTAL primeira hora anterior,PRECIPITAÇÃO TOTAL segunda hora anterior,PRECIPITAÇÃO TOTAL terceira hora anterior,VARIACAO PRIMEIRA HORA ANTERIOR PRESSAO,VARIACAO SEGUNDA HORA ANTERIOR PRESSAO,VARIACAO TERCEIRA HORA ANTERIOR PRESSAO,VARIACAO QUARTA HORA ANTERIOR PRESSAO,VARIACAO QUINTA HORA ANTERIOR PRESSAO,VARIACAO SEXTA HORA ANTERIOR PRESSAO,VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE,VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE,VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE,VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA ORVALHO,VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA ORVALHO,VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA ORVALHO,VARIACAO PRIMEIRA HORA ANTERIOR UMIDADE,VARIACAO SEGUNDA HORA ANTERIOR UMIDADE,VARIACAO TERCEIRA HORA ANTERIOR UMIDAD,DIRECAO DO VENTO PRIMEIRA HORA ANTERIOR,DIRECAO DO VENTO SEGUNDA HORA ANTERIOR,DIRECAO DO VENTO TERCEIRA HORA ANTERIOR,DIRECAO DO VENTO QUARTA HORA ANTERIOR,DIRECAO DO VENTO QUINTA HORA ANTERIOR,DIRECAO DO VENTO SEXTA HORA ANTERIOR,VELOCIDADE DO VENTO PRIMEIRA HORA ANTERIOR,VELOCIDADE DO VENTO SEGUNDA HORA ANTERIOR,VELOCIDADE DO VENTO TERCEIRA HORA ANTERIOR
0,2007-05-18,1.179457e+09,-22.988333,-43.190278,42.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,FORTE_COPACABANA,Outono,0,Noite,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df_nao_chuva = df[(df['Precip'] == 0)]

df_chuva = df[(df['Precip'] > 0) & (df['Precip'] < 25)]

df_chuva_extrema = df[(df['Precip'] >= 25)]

In [33]:
variaveis = ['Precip', 'ESTACAO','Dt_Hr']

In [35]:
df_nao_chuva = df_nao_chuva[variaveis]

In [37]:
df_nao_chuva.head()

    Precip           ESTACAO               Dt_Hr
18     0.0  FORTE_COPACABANA 2007-05-18 18:00:00
19     0.0  FORTE_COPACABANA 2007-05-18 19:00:00
35     0.0  FORTE_COPACABANA 2007-05-19 11:00:00
36     0.0  FORTE_COPACABANA 2007-05-19 12:00:00
37     0.0  FORTE_COPACABANA 2007-05-19 13:00:00

In [43]:
menor_dt_hr = df_nao_chuva.groupby('ESTACAO')['Dt_Hr'].min()
menor_dt_hr

ESTACAO
FORTE_COPACABANA   2007-05-18 18:00:00
JACAREPAGUA        2017-08-11 19:00:00
MARAMBAIA          2002-11-08 00:00:00
VILA_MILITAR       2007-04-13 16:00:00
Name: Dt_Hr, dtype: datetime64[ns]

In [45]:
# Jacarepagua começou em 2017 , então, vamos filtrar Dt_Hr a partir de 2017-08-13

In [47]:
# Converter Dt_Hr para datetime, se ainda não for
df_nao_chuva['Dt_Hr'] = pd.to_datetime(df_nao_chuva['Dt_Hr'])

df_nao_chuva = df_nao_chuva[df_nao_chuva['Dt_Hr'] >= '2017-08-13']

In [51]:
contagem_estacoes = df_nao_chuva['ESTACAO'].value_counts()  # Contagem absoluta
contagem_relativa = df_nao_chuva['ESTACAO'].value_counts(normalize=True)  # Contagem relativa (proporção)

# Exibir os resultados
print("Contagem Absoluta:")
print(contagem_estacoes)

print("\nContagem Relativa:")
print(contagem_relativa)

Contagem Absoluta:
ESTACAO
VILA_MILITAR        58228
JACAREPAGUA         57656
MARAMBAIA           57024
FORTE_COPACABANA    55202
Name: count, dtype: int64

Contagem Relativa:
ESTACAO
VILA_MILITAR        0.255263
JACAREPAGUA         0.252755
MARAMBAIA           0.249985
FORTE_COPACABANA    0.241997
Name: proportion, dtype: float64

In [59]:
df_chuva = df_chuva[variaveis]


df_chuva = df_chuva[df_chuva['Dt_Hr'] >= '2017-08-13']

In [63]:
contagem_estacoes = df_chuva['ESTACAO'].value_counts()  # Contagem absoluta
contagem_relativa = df_chuva['ESTACAO'].value_counts(normalize=True)  # Contagem relativa (proporção)

# Exibir os resultados
print("Contagem Absoluta:")
print(contagem_estacoes)

print("\nContagem Relativa:")
print(contagem_relativa)

Contagem Absoluta:
ESTACAO
JACAREPAGUA         5635
MARAMBAIA           4930
VILA_MILITAR        4484
FORTE_COPACABANA    4332
Name: count, dtype: int64

Contagem Relativa:
ESTACAO
JACAREPAGUA         0.290749
MARAMBAIA           0.254373
VILA_MILITAR        0.231361
FORTE_COPACABANA    0.223518
Name: proportion, dtype: float64

In [67]:
df_chuva_extrema = df_chuva_extrema[variaveis]


df_chuva_extrema = df_chuva_extrema[df_chuva_extrema['Dt_Hr'] >= '2017-08-13']

In [69]:
contagem_estacoes = df_chuva_extrema['ESTACAO'].value_counts()  # Contagem absoluta
contagem_relativa = df_chuva_extrema['ESTACAO'].value_counts(normalize=True)  # Contagem relativa (proporção)

# Exibir os resultados
print("Contagem Absoluta:")
print(contagem_estacoes)

print("\nContagem Relativa:")
print(contagem_relativa)

Contagem Absoluta:
ESTACAO
VILA_MILITAR        35
JACAREPAGUA         31
FORTE_COPACABANA    24
MARAMBAIA           21
Name: count, dtype: int64

Contagem Relativa:
ESTACAO
VILA_MILITAR        0.315315
JACAREPAGUA         0.279279
FORTE_COPACABANA    0.216216
MARAMBAIA           0.189189
Name: proportion, dtype: float64

In [83]:
import scipy.stats as stats

contagem_observada = df_chuva_extrema['ESTACAO'].value_counts()

contagem_esperada = contagem_observada.sum() / len(contagem_observada)

chi2_stat, p_value = stats.chisquare(contagem_observada, contagem_esperada)

# Exibir os resultados
print(f"Estatística Qui-Quadrado: {chi2_stat:.4f}")

print(f"Valor-p: {p_value:.4f}")

# Verificar significância
if p_value < 0.05:
    print("Rejeitamos H0: Existem diferenças significativas entre as estações.")
    
else:
    print("Não rejeitamos H0: Não há evidências de diferenças significativas entre as estações.")

Estatística Qui-Quadrado: 4.4234
Valor-p: 0.2192
Não rejeitamos H0: Não há evidências de diferenças significativas entre as estações.

In [75]:
contagem_observada.sum()

111

In [79]:
contagem_esperada

27.75