In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np 

from IPython.display import display

In [3]:
# Caminho para o arquivo Parquet
caminho_parquet = r"C:\Users\Pichau\INMET\TODAS_ESTACOES\TODAS_ESTACOES_CONCATENADO.parquet"

# Ler o arquivo Parquet
df = pd.read_parquet(caminho_parquet)

In [5]:
pd.set_option('display.max_columns', None)  # Exibe todas as colunas

df.head(1)

,Dt_Hr,timestamp,Lat,Long,Alt,Precip,Pres_Atm,Pres_Atm_max,Pres_Atm_min,Rad,Temp_Amb,Pto_Orv,Temp_Amb_max,Temp_Amb_min,Pto_Orv_max,Pto_Orv_min,Umidade_max,Umidade_min,Umidade,Vento_dir,Vento_raj,Vento_vel,ESTACAO,estacao_do_ano,hora,turno,PRECIPITAÇÃO TOTAL primeira hora anterior,PRECIPITAÇÃO TOTAL segunda hora anterior,PRECIPITAÇÃO TOTAL terceira hora anterior,VARIACAO PRIMEIRA HORA ANTERIOR PRESSAO,VARIACAO SEGUNDA HORA ANTERIOR PRESSAO,VARIACAO TERCEIRA HORA ANTERIOR PRESSAO,VARIACAO QUARTA HORA ANTERIOR PRESSAO,VARIACAO QUINTA HORA ANTERIOR PRESSAO,VARIACAO SEXTA HORA ANTERIOR PRESSAO,VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE,VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE,VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE,VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA ORVALHO,VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA ORVALHO,VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA ORVALHO,VARIACAO PRIMEIRA HORA ANTERIOR UMIDADE,VARIACAO SEGUNDA HORA ANTERIOR UMIDADE,VARIACAO TERCEIRA HORA ANTERIOR UMIDAD,DIRECAO DO VENTO PRIMEIRA HORA ANTERIOR,DIRECAO DO VENTO SEGUNDA HORA ANTERIOR,DIRECAO DO VENTO TERCEIRA HORA ANTERIOR,DIRECAO DO VENTO QUARTA HORA ANTERIOR,DIRECAO DO VENTO QUINTA HORA ANTERIOR,DIRECAO DO VENTO SEXTA HORA ANTERIOR,VELOCIDADE DO VENTO PRIMEIRA HORA ANTERIOR,VELOCIDADE DO VENTO SEGUNDA HORA ANTERIOR,VELOCIDADE DO VENTO TERCEIRA HORA ANTERIOR
0,2007-05-18,1.179457e+09,-22.988333,-43.190278,42.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,FORTE_COPACABANA,Outono,0,Noite,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_nao_chuva = df[(df['Precip'] == 0)]

df_chuva = df[(df['Precip'] > 0) & (df['Precip'] < 25)]

df_chuva_extrema = df[(df['Precip'] >= 25)]

In [9]:
variaveis = ['Precip', 'estacao_do_ano','Dt_Hr']

In [11]:
df_nao_chuva = df_nao_chuva[variaveis]

In [13]:
df_nao_chuva.head()

    Precip estacao_do_ano               Dt_Hr
18     0.0         Outono 2007-05-18 18:00:00
19     0.0         Outono 2007-05-18 19:00:00
35     0.0         Outono 2007-05-19 11:00:00
36     0.0         Outono 2007-05-19 12:00:00
37     0.0         Outono 2007-05-19 13:00:00

In [19]:
contagem_estacoes = df_nao_chuva['estacao_do_ano'].value_counts()  # Contagem absoluta
contagem_relativa = df_nao_chuva['estacao_do_ano'].value_counts(normalize=True)  # Contagem relativa (proporção)

# Exibir os resultados
print("Contagem Absoluta:")
print(contagem_estacoes)

print("\nContagem Relativa:")
print(contagem_relativa)

Contagem Absoluta:
estacao_do_ano
Inverno      130566
Primavera    122391
Outono       121995
Verão        117395
Name: count, dtype: int64

Contagem Relativa:
estacao_do_ano
Inverno      0.265191
Primavera    0.248587
Outono       0.247783
Verão        0.238440
Name: proportion, dtype: float64

In [21]:
df_chuva = df_chuva[variaveis]

In [23]:
contagem_estacoes = df_chuva['estacao_do_ano'].value_counts()  # Contagem absoluta
contagem_relativa = df_chuva['estacao_do_ano'].value_counts(normalize=True)  # Contagem relativa (proporção)

# Exibir os resultados
print("Contagem Absoluta:")
print(contagem_estacoes)

print("\nContagem Relativa:")
print(contagem_relativa)

Contagem Absoluta:
estacao_do_ano
Primavera    13681
Verão        12033
Outono        9691
Inverno       8100
Name: count, dtype: int64

Contagem Relativa:
estacao_do_ano
Primavera    0.314470
Verão        0.276589
Outono       0.222756
Inverno      0.186185
Name: proportion, dtype: float64

In [25]:
df_chuva_extrema = df_chuva_extrema[variaveis]

In [29]:
contagem_estacoes = df_chuva_extrema['estacao_do_ano'].value_counts()  # Contagem absoluta
contagem_relativa = df_chuva_extrema['estacao_do_ano'].value_counts(normalize=True)  # Contagem relativa (proporção)

# Exibir os resultados
print("Contagem Absoluta:")
print(contagem_estacoes)

print("\nContagem Relativa:")
print(contagem_relativa)

Contagem Absoluta:
estacao_do_ano
Verão        127
Outono        44
Primavera     26
Inverno        2
Name: count, dtype: int64

Contagem Relativa:
estacao_do_ano
Verão        0.638191
Outono       0.221106
Primavera    0.130653
Inverno      0.010050
Name: proportion, dtype: float64

In [35]:
import scipy.stats as stats

contagem_observada = df_chuva_extrema['estacao_do_ano'].value_counts()

contagem_esperada = contagem_observada.sum() / len(contagem_observada)

chi2_stat, p_value = stats.chisquare(contagem_observada, contagem_esperada)

# Exibir os resultados
print(f"Estatística Qui-Quadrado: {chi2_stat:.4f}")

print(f"Valor-p: {p_value:.4f}")

# Verificar significância
if p_value < 0.05:
    print("Rejeitamos H0: Existem diferenças significativas entre as estações.")
    
else:
    print("Não rejeitamos H0: Não há evidências de diferenças significativas entre as estações.")

Estatística Qui-Quadrado: 177.7839
Valor-p: 0.0000
Rejeitamos H0: Existem diferenças significativas entre as estações.